CREATE DATABASE KETTHUCHP
CREATE TABLE Subject(
sMaMon CHAR(10) NOT NULL PRIMARY KEY,
sTenMon NVARCHAR(30)
)
CREATE TABLE BOOK(
sMaSach CHAR(10) NOT NULL PRIMARY KEY,
sTieuDe NVARCHAR(30), 
fGia FLOAT,
sMaMon CHAR(10), 
sMoTa NVARCHAR(50)
)
ALTER TABLE dbo.BOOK ADD CONSTRAINT FK_MaMon FOREIGN KEY(sMaMon) REFERENCES dbo.Subject(sMaMon)
DELETE FROM dbo.BOOK WHERE sMaSach = 'MS08'
ALTER PROC insert_Book
@masach CHAR(10), @tensach NVARCHAR(30), @fGia FLOAT, @sMaMon CHAR(10), @sMoTa NVARCHAR(50)
AS 
BEGIN 

IF(NOT EXISTS (SELECT sTieuDe FROM dbo.BOOK WHERE sTieuDe LIKE @tensach))
BEGIN
INSERT INTO BOOK VALUES(@masach,@tensach, @fGia, @sMaMon, @sMoTa)
END 
END 
INSERT INTO  BOOK VALUES('MS08', 'abcxyz', 12, 'M01', 'SDJG')
SELECT *FROM dbo.BOOK WHERE sTieuDe = 'abcxyz'
CREATE PROC sp_book
@maMon CHAR(10)
AS 
BEGIN
SELECT *FROM dbo.BOOK WHERE sMaMon = @maMon
END 